# Generated by Django 4.0.4 on 2022-05-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='role',
            field=models.CharField(choices=[('Chairman', 'Chairman'), ('Deputy Chairman', 'Deputy Chairman'), ('General Secretary', 'General Secretary'), ('Deputy Secretary', 'Deputy Secretary'), ('Accountant', 'Accountant')], max_length=50),
        ),
    ]
