# Generated by Django 4.0.4 on 2022-05-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='role',
            field=models.CharField(choices=[('chairman', 'Chairman'), ('deputy_chairman', 'Deputy Chairman'), ('general_secretary', 'General Secretary'), ('deputy_secretary', 'Deputy Secretary'), ('accountant', 'Accountant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='community',
            name='role',
            field=models.CharField(choices=[('chairman', 'Chairman'), ('deputy_chairman', 'Deputy Chairman'), ('general_secretary', 'General Secretary'), ('deputy_secretary', 'Deputy Secretary'), ('accountant', 'Accountant'), ('member', 'Member')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='rank',
            field=models.CharField(choices=[('above', 'Above'), ('standard', 'Standard'), ('below', 'Below')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='type',
            field=models.CharField(choices=[('tithe', 'Tithe'), ('construction', 'Construction'), ('thanksgiving', 'Thanksgiving')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=50),
        ),
        migrations.AlterField(
            model_name='priest',
            name='status',
            field=models.CharField(choices=[('main', 'Main'), ('deputy', 'Deputy'), ('normal', 'Normal')], max_length=50),
        ),
    ]
